/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Discord: typeof import('./src/components/icons/Discord.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Introduction: typeof import('./src/components/Introduction.vue')['default']
    ModelsList: typeof import('./src/components/ModelsList.vue')['default']
    NavElement: typeof import('./src/components/NavElement.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    ProjectSection: typeof import('./src/components/ProjectSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    Share: typeof import('./src/components/icons/Share.vue')['default']
    ShareSocials: typeof import('./src/components/ShareSocials.vue')['default']
    TwitterSection: typeof import('./src/components/TwitterSection.vue')['default']
    X: typeof import('./src/components/icons/X.vue')['default']
    Youtube: typeof import('./src/components/icons/Youtube.vue')['default']
  }
}
